### ISSUE TITLE
Broken in master of coc-markdownlint

### ISSUE THREAD

**Issue by yaegassy** [fannheyward/coc-markdownlint#446]
It works fine with `:CocInstall coc-markdownlint`, but not with "master".

(I'm sorry if this is just a problem with my environment)

### [OK] :CocInstall coc-markdownlint

<img width="883" alt="1_coc-install-ok" src="https://user-images.githubusercontent.com/188642/135006307-fbf1a2b9-d224-4e36-a1b7-ecccb39dc84e.png">

### [NG] master 

<img width="882" alt="2_master_ng" src="https://user-images.githubusercontent.com/188642/135006356-26916411-8e41-445d-9926-80d24694af4d.png">

```
2021-09-28T10:10:07.351 ERROR (pid:16803) [extensions] - Error on createExtension coc-markdownlint from /Users/yaegassy/sandbox/coc-markdownlint/lib/index.js ReferenceError: URL is not defined
    at /Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:10184:33
    at Array.forEach (<anonymous>)
    at node_modules/markdownlint/lib/rules.js (/Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:10182:11)
    at __require (/Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:23:44)
    at node_modules/markdownlint/lib/markdownlint.js (/Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:10198:17)
    at __require (/Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:23:44)
    at Object.<anonymous> (/Users/yaegassy/sandbox/coc-markdownlint/lib/index.js:11851:38)
    at Module._compile (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:58012:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```

**Comment by yaegassy** [comment]
There are cases where the diagnostics is zero, but the sign and message remains.

It could be a problem with coc.nvim itself, or it could be due to breaking changes.

https://user-images.githubusercontent.com/188642/135014683-3dab0a4f-632e-4157-a172-117a3a4a6e33.mp4

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/3405

**Comment by fannheyward** [comment]
> There are cases where the diagnostics is zero, but the sign and message remains.

This has been fixed in coc-markdownlint v1.12.1.

**Comment by yaegassy** [comment]
I've checked. Thanks.

**Comment by fannheyward** [comment]
> URL is not defined

@yaegassy this has been fixed in coc.nvim https://github.com/neoclide/coc.nvim/commit/4526dfa95abae6e814692469d9a23185a04020a7.
